const ANCESTRIES = [
    "Human",
    "Human",
    "Human",
    "Human",
    "Kender",
    "Kender",
    "Dwarf",
    "Dwarf",
    "Elf",
    "Half-Elf"
];

const GENDERS = [
    "Male",
    "Female",
];

const AGES = [
    "Child",
    "Adolescent",
    "Adult",
    "Adult",
    "Adult",
    "Adult",
    "Middle-Aged",
    "Middle-Aged",
    "Elderly",
    "Ancient",
];

const OCCUPATIONS = [
    "Baker",
    "Carpenter",
    "Farmer",
    "Cook",
    "Cobbler",
    "Cooper",
    "Blacksmith",
    "Beggar",
    "Butcher",
    "Chandler",
    "Brewer",
    "Fisher",
];

const HAIR_COLORS = [
    "White",
    "Gray",
    "Black",
    "Brown",
    "Blonde",
    "Ginger",
];

const HAIR_STYLES = {
    Female: [
        "Long Braided",
        "Short Braided",
        "Long Loose",
        "Short Loose",
        "Bun",
    ],
    Male: [
        "Bald",
        "Short Braided",
        "Bowlcut",
        "Short Loose",
        "Bun",
    ],
};

const EYE_COLORS = [
    "Brown",
    "Brown",
    "Brown",
    "Blue",
    "Blue",
    "Green",
    "Green",
    "Gray",
    "Amber",
    "Heterochromia",
]

const APPEARANCES = [
    "Stocky",
    "Skinny",
    "Very tall",
    "Very short",
    "Beauty mark",
    "Scar on face",    
    "Muscular",
    "Frail",
    "Six fingers",
    "One arm",
    "Willowy build",
    "Sweaty",
    "Cleft chin",
    "One eye",
    "Bushy eyebrows",
];

const QUIRKS = [
    "Spits",
    "Always eating",
    "Moves quickly",
    "Apologteic",
    "Slaps backs",
    "Drops things",
    "Swears",
    "Makes puns",
    "Rare accent",
    "Easily spooked",
    "Forgetful",
    "Speaks quietly",
    "Twitches",
    "Moves slowly",
    "Speaks loudly",
    "Swaggers",
    "Smokes a pipe",
];

const NAMES = {
    Human: {
        Male: [
            "Adam",
            "Adelard",
            "Alain",
            "Albert",
            "Aldred",
            "Amos",
            "Arthur",
            "Bartholomew",
            "Bardolph",
            "Baudwin",
            "Bennet",
            "Bernard",
            "Bertram",
            "Blaise",
            "Brom",
            "Bryce",
            "Carlsby",
            "Castor",
            "Cedric",
            "Diggory",
            "Edwin",
            "Elias",
            "Elric",
            "Endric",
            "Faramond",
            "Galleron",
            "Gareth",
            "Geoffrey",
            "Gerald",
            "Gerard",
            "Gilbert",
            "Giles",
            "Godwin",
            "Gregory",
            "Griffith",
            "Gunther",
            "Harlow",
            "Hector",
            "Henry",
            "Herbert",
            "Hildebrandt",
            "Horace",
            "Hubert",
            "Hugh",
            "Isaac",
            "Isembard",
            "Jolly",
            "Kellan",
            "Lambert",
            "Leofwin",
            "Lionel",
            "Lios",
            "Lucan",
            "Mabon",
            "Manfred",
            "Merek",
            "Miles",
            "Milo",
            "Nigel",
            "Osric",
            "Percy",
            "Piers",
            "Randel",
            "Ranulf",
            "Roland",            
            "Rowan",
            "Rolf",
            "Theobald",
            "Thurstan",
            "Tobias",
            "Tristram",
            "Turstin",
            "Ulric",
            "Urian",
            "Walther",
            "Warin",
            "Warner",
            "William",
            "Wolfstand",
            "Wymond",
        ],
        Female: [
            "Adelina",
            "Aelina",
            "Agnes",
            "Althea",
            "Alma",
            "Anais",
            "Aldith",
            "Alice",
            "Alicia",
            "Aldith",
            "Alyson",
            "Amelina",
            "Amy",
            "Anne",
            "Avelina",
            "Avina",
            "Beatrice",
            "Beatrix",
            "Berta",
            "Blanche",
            "Bridget",
            "Bryn",
            "Cassandra",
            "Catelin",
            "Caterina",
            "Cicily",
            "Clarice",
            "Colleta",
            "Constance",
            "Corina",
            "Dassella",
            "Delia",
            "Edith",
            "Elle",
            "Elaine",
            "Eleanor",
            "Elena",
            "Eva",
            "Elizabeth",
            "Elysanda",
            "Emeline",
            "Emma",
            "Eveluna",
            "Evelyn",
            "Felicia",
            "Florence",
            "Genevieve",
            "Giselle",
            "Gwendolen",
            "Hannah",
            "Ida",
            "Isolda",
            "Ivette",
            "Johanna",
            "Kiara",
            "Laudine",
            "Lavina",
            "Leticia",
            "Lia",
            "Lillian",
            "Lena",
            "Linota",
            "Lucy",
            "Lunette",
            "Mary",
            "Maria",
            "Marion",
            "Masselie",
            "Mathilda",
            "Maude",
            "Meliora",
            "Miriel",
            "Mirielda",
            "Milicent",
            "Moira",
            "Myrtle",
            "Nesta",
            "Nicola",
            "Nora",
            "Orella",
            "Philippa",
            "Regina",
            "Rosalin",
            "Roanna",            
            "Rosamund",
            "Sabella",
            "Sabina",
            "Sara",
            "Sela",
            "Semila",
            "Sybil",
            "Thora",
            "Vivan",
        ],
    },
    Kender: {
        Male: [],
        Female: [],
    },
    Dwarf: {
        Male: [],
        Female: [],
    },
    Elf: {
        Male: [
            "Ravos",
            "Farondas",
            "Kierenas",
            "Riardenas",
            "Arlomas",
            "Saramiras",
            "Elindos",
            "Cydaros",
            "Rinarielos",
            "Tiramelos",
            "Taenaranos",
            "Ailunos",
            "Ailas",
            "Ornthalas",
            "Mitalaras",
            "Erlanas",
            "Elandoras",
            "Alluinas",
            "",
            "",
        ],
        Female: [
            "Sarenia",
            "Imeria",
            "Isoldena",
            "Mirenella",
            "Allindra",
            "Sylara",
            "Vedana",
            "Ophelia",
            ""
        ],
    },
}



export const NPCs = () => {
    const handleClick = (event) => {
        let trap = TRAPS[Math.floor(Math.random() * TRAPS.length)];
        let trigger = TRIGGERS[Math.floor(Math.random() * TRIGGERS.length)];
        let effect = EFFECTS[Math.floor(Math.random() * EFFECTS.length)];
        event.currentTarget.nextElementSibling.innerText = `${trap}, ${trigger}, ${effect}`;
    };

    return (
        <section className={"d-flex mt-2"}>
            <div>
                <button
                    className={"btn btn-primary btn-smme-2 "}
                    type={"button"}
                    onClick={handleClick}
                >
                    Trap
                </button>
            </div>
            <p className={"trap-description"}></p>
        </section>
    );
};