import { Location } from "./classes/location.jsx";
import { Link } from "react-router-dom";

export const LINKS = {
    ability: {
        herbalism: <Link to={"/mechanics/abilities#herbalism"}>Herbalism</Link>,
    },
    attribute: <Link to={"/mechanics/attributes"}>attribute</Link>,
    attributes: <Link to={"/mechanics/attributes"}>attributes</Link>,
    condition: <Link to={"/mechanics/conditions"}>condition</Link>,
    conditions: <Link to={"/mechanics/health#conditions"}>conditions</Link>,
    disease: <Link to={"/mechanics/health#disease"}>disease</Link>,
    poison: <Link to={"/mechanics/health#poison"}>poison</Link>,
    push: <Link to={"/mechanics/general#push-your-luck"} > Push Your Luck</Link>,
    // skill: <Link to={"/mechanics/skills/"}>skill</Link>,
    skill: {
        acrobatics: <Link to={"/mechanics/skills#acrobatics"}>Acrobatics</Link>,
        alchemy: <Link to={"/mechanics/skills#alchemy"}>Alchemy</Link>,
        arcane: <Link to={"/mechanics/skills#arcane-casting"}>Arcane Casting</Link>,
        // bartering: <Link to={"/mechanics/skills#bartering"}>Bartering</Link>,
        beast: <Link to={"/mechanics/skills#beast-lore"}>Beast Lore</Link>,
        bluff: <Link to={"/mechanics/skills#bluff"}>Bluff</Link>,
        climbing: <Link to={"/mechanics/skills#climbing"}>Climbing</Link>,
        cooking: <Link to={"/mechanics/skills#cooking"}>Cooking</Link>,
        crafting: <Link to={"/mechanics/skills#crafting"}>Crafting</Link>,
        divine: <Link to={"/mechanics/skills#divine-casting"}>Divine Casting</Link>,
        dodge: <Link to={"/mechanics/skills#dodge"}>Dodge</Link>,
        herbalism: <Link to={"/mechanics/skills#herbalism"}>Herbalism</Link>,
        medicine: <Link to={"/mechanics/skills#medicine"}>Medicine</Link>,
        myths: <Link to={"/mechanics/skills#myths-and-legends"}>Myths and Legends</Link>,
        perception: <Link to={"/mechanics/skills#perception"}>Perception</Link>,
        performance: <Link to={"/mechanics/skills#performance"}>Performance</Link>,
        persuasion: <Link to={"/mechanics/skills#persuasion"}>Persuasion</Link>,
        riding: <Link to={"/mechanics/skills#riding"}>Riding</Link>,
        seamanship: <Link to={"/mechanics/skills#seamanship"}>Seamanship</Link>,
        sleight: <Link to={"/mechanics/skills#sleight-of-hand"}>Sleight Of Hand</Link>,
        stealth: <Link to={"/mechanics/skills#stealth"}>Stealth</Link>,
        survival: <Link to={"/mechanics/skills#survival"}>Survival</Link>,
        swimming: <Link to={"/mechanics/skills#swimming"}>Swimming</Link>,
        tinkering: <Link to={"/mechanics/skills#tinkering"}>Tinkering</Link>,
        tracking: <Link to={"/mechanics/skills#tracking"}>Tracking</Link>,
    },
    skills: <Link to={"/mechanics/skills"}>skills</Link>,
    mechanics: {
        combat: {
            sneakattack: <Link to={"/mechanics/combat#sneak-attack"}>Sneak Attack</Link>,
        }
    }
}

export const SPECIES = [
    "Humans",
    "Half-Elves",
    "Kender",
    "Dwarves",
    "Elves",
];

export const LOCATIONS = [
    new Location(
        {
            name: "Krynn",
            population: 12,
            description: "Its a planet",
        }
    ),
];

export const SKILLS = {
    acrobatics: { attr: "dex", score: 0, name: "Acrobatics", description: "Used for jumping, balancing, and similar physical actions." },
    alchemy: { attr: "int", score: 0, name: "Alchemy", description: "This skill lets you identify alchemical items. With the Alchemist ability and proper equipment and ingredients, you can craft alchemical items as well." },
    arcaneCasting: { attr: "int", score: 0, name: "Arcane Casting", description: "You must be a Mage to use this skill. This skill is used for casting Arcane spells, as well as identifying Arcane spells cast by others. You must be a Mage to have Arcane Casting as a class skill." },
    beastLore: { attr: "int", score: 0, name: "Beast Lore", description: "The world is full of common and rare animals and beasts. Beast Lore is rolled when trying to identify an animal or Monster, or to discern the behaviors, abilities, or weaknesses of an animal you have identified.", },
    bluff: { attr: "cha", score: 0, name: "Bluff", description: "To quickly come up with a convincing lie can be an invaluable skill as an adventurer; that is where this skill comes into play. If your bluff is unconvincing, you gain a Bane on your roll. If your bluff is completely unbelievable, the roll fails automatically, no matter how well you deliver it." },
    climbing: { attr: "str", score: 0, name: "Climbing", description: "The difficulty of climbing depends on the surface being scaled. Climbing a tree or ladder probably doesn't require a roll, while climbing a stone wall without equipment might inflict a Bane, or not be possible at all." },
    cooking: { attr: "int", score: 0, name: "Cooking", description: "Cooking is used to make food safe for consumption. Critical failure yields food that looks safe but is an Emetic Poison. Failure ruins the ingredients. Success yields a regular meal. Critical success creates an excellent meal that adds 1d6 to your healing during your next Long Rest." },
    crafting: { attr: "str", score: 0, name: "Crafting", description: "As an adventurer, you must often repair your gear when it Breaks. Typically, it takes one Shift to repair a Broken item, assuming you have the necessary tools and supplies." },
    divineCasting: { attr: "wil", score: 0, name: "Divine Casting", description: "Divine Casting is used by clerics to wield their deity's power (that is, cast spells). You must be a cleric to have Divine Casting as a class skill." },
    dodge: { attr: "dex", score: 0, name: "Dodge", description: "Dodge is used when attempting to Dodge an attack or flee combat." },
    herbalism: { attr: "int", score: 0, name: "Herbalism", description: "This skill lets you identify plants and herbal items. With the Herbalist ability, proper equipment, and ingredients, you can craft herbal items as well." },
    medicine: {
        attr: "int", score: 0, name: "Medicine", description: <span>There is significant risk when adventuring. This skill can be used to: <ul><li>Administer Care (During a short rest, increase the HP regained by another character by 1d6. A Healer's Kit is required.)</li><li>First Aid (Stabilize a character that is 0 HP. This check has a Bane unless you have Bandages.)
        </li><li>Treat Disease (Use your Medicine check in place of another character's Con check vs disease. Requires a Healer's Kit.)</li><li>Treat An Injury (Reduces the healing time of an injury by 1 day per treatment. This requires Surgical Tools and one Shift per treatment.).</li></ul></span>
    },
    mythsAndLegends: { attr: "int", score: 0, name: "Myths and Legends", description: "Myths and Legends is used when trying to recall stories of old times or distant lands, or when trying to understand links to the past." },
    perception: { attr: "int", score: 0, name: "Perception", description: "Perception is used to search for hidden things and creatures, and to notice something out of the corner of your eye." },
    performance: { attr: "cha", score: 0, name: "Performance", description: "Performance is rolled when you attempt to sing a song, recite a poem, deliver a joke, dance, or in some manner entertain a crowd." },
    persuasion: { attr: "cha", score: 0, name: "Persuasion", description: "Persuasion is used when you try to charm, threaten, or reason with an NPC in order to get them to do something, or change their mind about something. If you succeed, the NPC does what you ask, but probably at some cost to you. A critical success means there is no cost. Failure means the NPC doesn't cooperate, and a critical failure means the NPC becomes unfriendly, or even hostile. Persuasion may also be used to Rally a character at 0 HP. A Rallied character must continue making Death Saves, but may continue acting." },
    riding: { attr: "dex", score: 0, name: "Riding", description: "Casually riding a horse, pony, mule, goat, dog, or other mundane animal doesn't require a Riding check. However, galloping, tricks, and combat maneuvers do require Riding checks. Checks receive a Bane if your mount doesn't have appropriate equipment." },
    seamanship: { attr: "int", score: 0, name: "Seamanship", description: "Anyone can row a boat or paddle a canoe slowly, but challenging conditions require a Seamanship check." },
    sleightOfHand: { attr: "dex", score: 0, name: "Sleight of Hand", description: "This skill is used when you are trying to pick a pocket or do tricky things with your hands." },
    stealth: { attr: "dex", score: 0, name: "Stealth", description: "Stealth is used for avoiding detection, and is opposed by Perception." },
    survival: { attr: "int", score: 0, name: "Survival", description: "This skill is used for navigating, fishing, foraging, and locating safe camp sites. Fishing requires suitable equipment or a weapon like a spear or trident." },
    swimming: { attr: "str", score: 0, name: "Swimming", description: "Under normal circumstances, characters can float for one Shift without making Swimming checks. Your movement rate is halved while swimming. Ranged attacks are impossible, and melee attacks receive a Bane, while swimming. The frequency at which you must make Swimming checks depends on the environment and your armor." },
    tinkering: { attr: "int", score: 0, name: "Tinkering", description: "Tinkering is not just the domain of Tinker Gnomes; many characters enjoy working on small mechanical devices. This skill is used for picking locks (requiring lockpicks), arming and disarming traps, and similar activities." },
    tracking: { attr: "int", score: 0, name: "Tracking", description: "Tracking is used for locating and following the tracks of animals, people, and Monsters. It is integral to Hunting. Identifying the tracks you are following might require another skill, such as Beast Lore." },
    axes: { attr: "str", score: 0, name: "Axes", description: "A skill used for combat with axes of all kinds, including when thrown." },
    bludgeons: { attr: "str", score: 0, name: "Bludgeons", description: "Used for combat with hammer, clubs, maces, and other blunt weapons." },
    bows: { attr: "dex", score: 0, name: "Bows", description: "A skill for attacks with all types of bows, except crossbows." },
    brawling: { attr: "str", score: 0, name: "Brawling", description: "Used for unarmed combat with fists, feet, teeth, or claws." },
    crossbows: { attr: "dex", score: 0, name: "Crossbows", description: "This skill is used for attacks with all kinds of crossbows." },
    knives: { attr: "dex", score: 0, name: "Knives", description: "This skill is used for combat with knives and daggers, including when thrown." },
    slings: { attr: "dex", score: 0, name: "Slings", description: "This skill is used when attacking with slings of all sorts." },
    spears: { attr: "str", score: 0, name: "Spears", description: "A skill used for combat with spears and tridents, including when thrown. It also covers lances." },
    staves: { attr: "dex", score: 0, name: "Staves", description: "Use this skill when fighting with a staff." },
    swords: { attr: "str", score: 0, name: "Swords", description: "Used for combat with all types of swords." },
};

export const makePricingVerbose = (price) => {
    if (typeof price === "string") {
        return price;
    } else {
        if (Number.isInteger(price)) {
            return `${price} gold`;
        } else {
            let priceAsString = price.toString().split(".");

            let gp = priceAsString[0];
            if (gp === "0") gp = null;

            let sp, cp;
            if (priceAsString[1].length === 2) {
                let decimalsSplit = priceAsString[1].split("");
                sp = decimalsSplit[0];
                if (sp === "0") sp = null;
                cp = decimalsSplit[1];
                if (cp === "0") cp = null;
            } else {
                sp = priceAsString[1];
                if (sp === "0") sp = null;
            }
            let response = "";
            if (gp) response += `${gp} gold `;
            if (sp) response += `${sp} silver `;
            if (cp) response += `${cp} copper `;
            return response;
        }
    }
};

export const NPCS = [
    {
        name: "Bandit",
        movement: 6,
        damageBonus: "DEX + 1d4",
        hp: 12,
        wp: 0,
        skills: "Perception: 10, Dodge 8",
        armor: "N/A",
        weapons: [
            "Hunting Bow (12), 1d10 + 1d4, Durability 3",
            "Short Sword (12), 1d10 + 1d4, Durability 15",
        ],
        abilities: [],
        quantity: 6,
    },
    {
        name: "Bandit Chief",
        movement: 6,
        damageBonus: "STR + 1d6",
        hp: 26,
        wp: 16,
        skills: "Perception: 10, Dodge 8",
        armor: "Ring Mail (4)",
        weapons: [
            "Long Sword (16), 2d8 + 1d6, Durability 15",
            "Round Shield, Durability 12",
        ],
        abilities: [
            "Berserker"
        ],
        quantity: 1,
    },
    {
        name: "Cultist",
        movement: 6,
        damageBonus: "DEX + 1d4",
        hp: 12,
        wp: 0,
        skills: "Perception: 12, Dodge 8",
        armor: "Padded (1)",
        weapons: [
            "Dagger (14), 1d6 + 1d4, Durability 9",
        ],
        abilities: [],
        quantity: 4,
    },
    {
        name: "Goblin Scout",
        movement: 6,
        damageBonus: "N/A",
        hp: 9,
        wp: 8,
        skills: "Perception: 10, Dodge: 10, Stealth: 12",
        armor: "None",
        weapons: [
            "Club (10), 1d8, Durability 6",
            "Sling (10), 1d8, Durability 0",
        ],
        quantity: 3,
    },
    {
        name: "Goblin Warrior",
        movement: 6,
        damageBonus: "N/A",
        hp: 10,
        wp: 8,
        skills: "Perception: 10, Dodge: 10, Stealth: 12",
        armor: "Padded (1)",
        weapons: [
            "Short Spear (12), 2d4, Durability 9",
            "Club (12), 1d8, Durability 6",
        ],
        quantity: 4,
    },
    {
        name: "Guard",
        movement: 6,
        damageBonus: "STR + 1d4",
        hp: 12,
        wp: 0,
        skills: "Perception: 12, Dodge 8",
        armor: "Boiled Leather (2)",
        weapons: [
            "Short Sword (12), 1d10 + 1d4, Durability 15",
        ],
        abilities: [],
        quantity: 2,
    },
    {
        name: "Hobgoblin Fighter",
        movement: 6,
        damageBonus: "N/A",
        hp: 12,
        wp: 8,
        skills: "Perception: 10, Dodge: 12, Stealth: 10",
        armor: "Boiled Leather (2)",
        weapons: [
            "Hand Axe (12), 1d10, Durability 9",
            "Short Spear (12), 2d4, Durability 9",
        ],
        quantity: 3,
    },
    {
        name: "Hobgoblin Scout",
        movement: 6,
        damageBonus: "N/A",
        hp: 9,
        wp: 8,
        skills: "Perception: 12, Dodge: 12, Stealth: 14",
        armor: "Padded (1)",
        weapons: [
            "Hunting Bow (12), 1d10, Durability 3",
            "Dagger (12), 2d4, Durability 9",
        ],
        quantity: 1,
    },
    {
        name: "Hobgoblin Thief",
        movement: 6,
        damageBonus: "DEX + 1d4",
        hp: 7,
        wp: 8,
        skills: "Perception: 12, Dodge: 12, Stealth: 14",
        armor: "Padded (1)",
        weapons: [
            "Dagger (12), 2d4 + 1d4, Durability 9",
            "Sling (12), 1d8 + 1d4, Durability 0",
        ],
        quantity: 1,
    },
    {
        name: "Hunter",
        movement: 6,
        damageBonus: "DEX + 1d4",
        hp: 13,
        wp: 0,
        skills: "Perception: 10, Dodge 8",
        armor: "N/A",
        weapons: [
            "Hunting Bow (12), 1d10 + 1d4, Durability 3",
            "Dagger (12), 2d4 + 1d4, Durability 9",
        ],
        abilities: [],
        quantity: 1,
    },
    {
        name: "Lizardfolk Hunter",
        movement: 6,
        damageBonus: "DEX + 1d4",
        hp: 9,
        wp: 8,
        skills: "Perception: 12, Dodge: 12, Stealth: 14",
        armor: "Natural (1)",
        weapons: [
            "Hunting Bow (12), 1d10 + 1d4, Durability 3",
            "Dagger (12), 2d4 + 1d4, Durability 9",
        ],
        quantity: 2,
    },
    {
        name: "Lizardfolk Warrior",
        movement: 6,
        damageBonus: "STR + 1d4",
        hp: 10,
        wp: 8,
        skills: "Perception: 12, Dodge: 12, Stealth: 10",
        armor: "Boiled Leather (2)",
        weapons: [
            "Spiked Club (12), 1d10 + 1d4, Durability 6",
            "Short Spear (12), 2d4 + 1d4, Durability 9",
        ],
        quantity: 3,
    },
    {
        name: "Ogre Chieftan",
        movement: 6,
        damageBonus: "STR + 1d6",
        hp: 30,
        wp: 16,
        skills: "Perception: 12, Dodge: 8, Stealth: 6",
        armor: "Natural (1)",
        weapons: [
            "War Club (10), 2d8 + 1d6, Durability 9",
            "Short Spear (10), 2d4 + 1d6, Durability 9",
        ],
        quantity: 1,
    },
    {
        name: "Ogre Warrior",
        movement: 6,
        damageBonus: "STR + 1d6",
        hp: 16,
        wp: 12,
        skills: "Perception: 8, Dodge: 6, Stealth: 6",
        armor: "Natural (1)",
        weapons: [
            "War Club (10), 2d8 + 1d6, Durability 9",
            "Short Spear (10), 2d4 + 1d6, Durability 9",
        ],
        quantity: 2,
    },
    {
        name: "Satyr",
        movement: 5,
        damageBonus: "N/A",
        hp: 10,
        wp: 12,
        skills: "Bluff 10, Dodge 10, Performance 14, Persuasion 12",
        armor: "Boiled Leather (2)",
        weapons: [
            "Short Spear (10), 2d4 + 1d4, Durability 9",
        ],
        quantity: 1,
    },
    {
        name: "Skeleton Archer",
        movement: 6,
        damageBonus: "N/A",
        hp: 8,
        wp: 0,
        skills: "Perception: 8, Dodge 6",
        armor: "Padded (1)",
        weapons: [
            "Hunting Bow (12), 1d10, Durability 3",
            "Dagger (10), 2d4, Durability 9",
        ],
        abilities: [
            "Damage Resistance: Piercing",
            "Fear immunity",
            "Persuasion immunity",
        ],
        quantity: 4,
    },
    {
        name: "Skeleton Champion",
        movement: 6,
        damageBonus: "STR + 1d6",
        hp: 24,
        wp: 15,
        skills: "Perception: 12, Dodge 8",
        armor: "Ring Mail (4)",
        weapons: [
            "Long Sword (16), 2d8 + 1d6, Durability 15",
            "Round Shield, Durability 12",
        ],
        abilities: [
            "Veteran",
            "Defensive",
            "Double Slash",
            "Damage Resistance: Piercing",
            "Fear immunity",
            "Persuasion immunity",
        ],
        quantity: 1,
    },
    {
        name: "Skeleton Warrior",
        movement: 6,
        damageBonus: "N/A",
        hp: 8,
        wp: 0,
        skills: "Perception: 8, Dodge 6",
        armor: "Boiled Leather (2)",
        weapons: [
            "Short Sword (12), 1d10, Durability 15",
        ],
        abilities: [
            "Damage Resistance: Piercing",
            "Fear immunity",
            "Persuasion immunity",
        ],
        quantity: 4,
    },
    {
        name: "Thief",
        movement: 6,
        damageBonus: "DEX + 1d4",
        hp: 10,
        wp: 0,
        skills: "Perception: 12, Dodge 8",
        armor: "N/A",
        weapons: [
            "Dagger (14), 1d6 + 1d4, Durability 9",
        ],
        abilities: [],
        quantity: 1,
    },
    {
        name: "Villager",
        movement: 6,
        damageBonus: "N/A",
        hp: 8,
        wp: 0,
        skills: "Perception: 8, Dodge 6",
        armor: "N/A",
        weapons: [
            "Club (8), 1d4, Durability 3",
        ],
        abilities: [],
        quantity: 8,
    },
];

export const FOES = [
    NPCS[0],
    NPCS[1],
    NPCS[3],
    NPCS[4],
    NPCS[5],
    NPCS[6],
    NPCS[7],
    NPCS[8],
    NPCS[11],
    NPCS[12],
    NPCS[13],
    NPCS[14],
    NPCS[15],
];

export const BIOMES = {
    village: "Village",
    city: "City",
    grasslands: "Grasslands",
    woodlands: "Woodlands",
    subalpine: "Sub-Alpine", // Sub-alpine refers to a high-elevation ecological zone just below the treeline in mountains. This zone is characterized by cool climates, deep snow, and hardy coniferous forests.
    freshwater: "Fresh Water",
    wetlands: "Wetlands",
    desert: "Deserts",
    mountains: "Mountains",
    swamps: "Swamps",
    hills: "Hills",
    jungle: "Jungle",
    wasteland: "Wasteland",
    glacier: "Glacier",
};

export const ANIMALS = [
    {
        name: "Badger",
        movement: 6,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 14",
            "Stealth 12",
        ],
        size: 1,
        biomes: [
            BIOMES.grasslands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Bear, Black",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 8",
            "Perception 10",
        ],
        size: 3,
        biomes: [
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Bear, Brown",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 8",
            "Perception 10",
        ],
        size: 4,
        biomes: [
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Bear, Grizzly",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 8",
            "Perception 10",
        ],
        size: 5,
        biomes: [
            BIOMES.woodlands,
            BIOMES.subalpine,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Beaver",
        movement: "3/14",
        skills: [
            "Brawling 8",
            "Dodge 14",
            "Perception 12",
            "Swimming 16",
        ],
        size: 1,
        biomes: [
            BIOMES.wetlands,
            BIOMES.freshwater,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Boar",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 8",
            "Perception 10",
        ],
        size: 3,
        biomes: [
            BIOMES.woodlands,
            BIOMES.grasslands,
            BIOMES.wetlands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Bull",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 8",
            "Perception 8",
        ],
        size: 4,
        availability: 1,
        cost: 30,
        biomes: [],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Cat",
        movement: 8,
        skills: [
            "Brawling 8",
            "Dodge 14",
            "Perception 12",
            "Stealth 16",
        ],
        size: 0,
        availability: 0,
        cost: 0.2,
        biomes: [
            BIOMES.village,
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Chicken",
        movement: "4/6",
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 10",
        ],
        size: 0,
        availability: 0,
        cost: 0.05,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Cow",
        movement: 5,
        skills: [
            "Brawling 8",
            "Dodge 8",
            "Perception 8",
        ],
        size: 4,
        availability: 1,
        cost: 15,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Deer",
        movement: 12,
        skills: [
            "Brawling 10",
            "Dodge 12",
            "Perception 12",
        ],
        size: 4,
        biomes: [
            BIOMES.mountains,
            BIOMES.woodlands,
            BIOMES.grasslands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Dog, Companion",
        movement: 9,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 12",
            "Stealth 12",
        ],
        size: 2,
        availability: 0,
        cost: 10,
        biomes: [
            BIOMES.village,
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Dog, Guard",
        movement: 9,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 12",
            "Stealth 12",
        ],
        size: 2,
        availability: 0,
        cost: 25,
        biomes: [
            BIOMES.village,
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Dog, Hunting",
        movement: 9,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 14",
            "Stealth 12",
        ],
        size: 2,
        availability: 0,
        cost: 40,
        biomes: [
            BIOMES.village,
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Dog, War",
        movement: 9,
        skills: [
            "Brawling 14",
            "Dodge 10",
            "Perception 12",
            "Stealth 8",
        ],
        size: 2,
        availability: 1,
        cost: 40,
        biomes: [
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Donkey",
        movement: 9,
        skills: [
            "Brawling 10",
            "Dodge 6",
            "Perception 10",
        ],
        size: 3,
        availability: 1,
        cost: 12,
        biomes: [
            BIOMES.village,
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Duck",
        movement: "4/12",
        skills: [
            "Brawling 8",
            "Dodge 10",
            "Perception 10",
            "Swimming 16",
        ],
        size: 0,
        availability: 0,
        cost: 0.06,
        biomes: [
            BIOMES.wetlands,
            BIOMES.freshwater,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Elk",
        movement: 10,
        skills: [
            "Brawling 10",
            "Dodge 12",
            "Perception 12",
        ],
        size: 5,
        biomes: [
            BIOMES.woodlands,
            BIOMES.mountains,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Ferret",
        movement: 12,
        skills: [
            "Brawling 12",
            "Dodge 12",
            "Perception 12",
            "Stealth 14",
        ],
        size: 0,
        biomes: [
            BIOMES.woodlands,
            BIOMES.grasslands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Fox",
        movement: 6,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 12",
            "Stealth 14",
        ],
        size: 1,
        biomes: [
            BIOMES.woodlands,
            BIOMES.grasslands,
            BIOMES.mountains,
            BIOMES.desert,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Goat, Domestic",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 12",
            "Perception 10",
        ],
        size: 2,
        availability: 0,
        cost: 5,
        biomes: [
            BIOMES.village,
            BIOMES.grasslands,
        ],
        huntable: false,
        fightsBack: true,
    },
    {
        name: "Goat, Mountain",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 12",
            "Perception 10",
        ],
        size: 2,
        availability: 0,
        cost: 5,
        biomes: [
            BIOMES.mountains,
            BIOMES.subalpine,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Goose",
        movement: "4/12",
        skills: [
            "Brawling 8",
            "Dodge 10",
            "Perception 10",
            "Swimming 16",
        ],
        size: 1,
        availability: 1,
        cost: 0.1,
        biomes: [
            BIOMES.freshwater,
            BIOMES.wetlands,
            BIOMES.grasslands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Hawk",
        movement: "4/16",
        skills: [
            "Brawling 12",
            "Dodge 12",
            "Perception 16",
        ],
        size: 1,
        availability: 2,
        cost: 250,
        biomes: [
            BIOMES.city,
            BIOMES.woodlands,
            BIOMES.grasslands,
            BIOMES.desert,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Horse, Draft",
        movement: 13,
        skills: [
            "Brawling 10",
            "Dodge 8",
            "Perception 12",
        ],
        size: 4,
        availability: 1,
        cost: 350,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Horse, Riding",
        movement: 13,
        skills: [
            "Brawling 10",
            "Dodge 8",
            "Perception 12",
        ],
        size: 4,
        availability: 1,
        cost: 275,
        biomes: [
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Horse, War",
        movement: 13,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 12",
        ],
        size: 5,
        availability: 2,
        cost: 700,
        biomes: [
            BIOMES.city,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Llama",
        movement: 18,
        skills: [
            "Brawling 10",
            "Dodge 12",
            "Perception 12",
        ],
        size: 3,
        availability: 2,
        cost: 75,
        biomes: [
            BIOMES.subalpine,
            BIOMES.mountains,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Moose",
        movement: 10,
        skills: [
            "Brawling 10",
            "Dodge 8",
            "Perception 10",
        ],
        size: 5,
        biomes: [
            BIOMES.woodlands,
            BIOMES.wetlands,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Mountain Lion",
        movement: 12,
        skills: [
            "Brawling 14",
            "Dodge 12",
            "Perception 14",
            "Stealth 14",
        ],
        size: 3,
        biomes: [
            BIOMES.grasslands,
            BIOMES.subalpine,
            BIOMES.mountains,
            BIOMES.woodlands,
            BIOMES.hills,
        ],
        huntable: false,
        fightsBack: true,
    },
    {
        name: "Mule",
        movement: 9,
        skills: [
            "Brawling 10",
            "Dodge 6",
            "Perception 10",
        ],
        size: 3,
        availability: 1,
        cost: 12,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Ox",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 8",
            "Perception 8",
        ],
        size: 4,
        availability: 1,
        cost: 23,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Partridge",
        movement: "4/12",
        skills: [
            "Brawling 8",
            "Dodge 10",
            "Perception 10",
        ],
        size: 0,
        availability: 0,
        cost: 0.05,
        biomes: [
            BIOMES.grasslands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Pheasant",
        movement: "4/12",
        skills: [
            "Brawling 8",
            "Dodge 10",
            "Perception 10",
        ],
        size: 0,
        availability: 0,
        cost: 0.05,
        biomes: [
            BIOMES.grasslands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Pig, Domestic",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 2,
        availability: 0,
        cost: 6,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Pig, Wild",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 2,
        biomes: [
            BIOMES.grasslands,
            BIOMES.wetlands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Pigeon",
        movement: "4/12",
        skills: [
            "Brawling 8",
            "Dodge 10",
            "Perception 10",
        ],
        size: 0,
        availability: 0,
        cost: 0.02,
        biomes: [
            BIOMES.mountains,
            BIOMES.subalpine,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Porcupine",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 1,
        biomes: [
            BIOMES.grasslands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Possum",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.grasslands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Rabbit",
        movement: 6,
        skills: [
            "Brawling 8",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.grasslands,
            BIOMES.subalpine,
            BIOMES.wetlands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Rat",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.desert,
            BIOMES.freshwater,
            BIOMES.grasslands,
            BIOMES.mountains,
            BIOMES.subalpine,
            BIOMES.swamps,
            BIOMES.wetlands,
            BIOMES.woodlands,
            BIOMES.village,
            BIOMES.city,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Raccoon",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.grasslands,
            BIOMES.woodlands,
            BIOMES.wetlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Sheep",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 12",
            "Perception 10",
        ],
        size: 2,
        availability: 0,
        cost: 4,
        biomes: [
            BIOMES.village,
        ],
        huntable: false,
        fightsBack: false,
    },
    {
        name: "Snake",
        movement: 8,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 12",
        ],
        size: 1,
        biomes: [
            BIOMES.desert,
            BIOMES.freshwater,
            BIOMES.grasslands,
            BIOMES.mountains,
            BIOMES.subalpine,
            BIOMES.swamps,
            BIOMES.wetlands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Skunk",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.grasslands,
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Squirrel",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.woodlands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Wari",
        movement: 12,
        skills: [
            "Brawling 12",
            "Dodge 10",
            "Perception 12",
        ],
        size: 3,
        availability: 1,
        cost: 30,
        biomes: [
            BIOMES.grasslands,
            BIOMES.hills,
        ],
        huntable: true,
        fightsBack: true,
    },
    {
        name: "Weasel",
        movement: 6,
        skills: [
            "Brawling 10",
            "Dodge 10",
            "Perception 8",
        ],
        size: 0,
        biomes: [
            BIOMES.woodlands,
            BIOMES.grasslands,
        ],
        huntable: true,
        fightsBack: false,
    },
    {
        name: "Wolf",
        movement: 12,
        skills: [
            "Brawling 14",
            "Dodge 12",
            "Perception 14",
            "Stealth 14",
        ],
        size: 3,
        biomes: [
            BIOMES.grasslands,
            BIOMES.subalpine,
            BIOMES.mountains,
            BIOMES.woodlands,
            BIOMES.hills,
        ],
        huntable: false,
        fightsBack: true,
    },
];

export const MEAT = [
    "1",
    "1d3",
    "1d4",
    "1d6",
    "1d8",
    "2d4",
    "1d10",
];

export const DAMAGE = [
    "1d3",
    "1d4",
    "1d6",
    "1d8",
    "1d10",
    "1d12",
    "2d6",
];

export const STORAGE_KEYS = {
    selectedBiome: "patlance_selected-biome",
    currentDateIndex: "patlance_current-date-index",
    animalList: "patlance_animal-list",
    showHuntable: "patlance_show-huntable",
};


const TRAITS = {
    alcoholTolerance: "These creatures can drink copious amounts of alcohol without getting particularly drunk.",
    aquatic: "Aquatic creatures have unique means of moving and breathing under water. They can stay above the surface for one Stretch without any problems, but after that they suffer 1D6 damage per Stretch spent on land.",
    fear: {
        chickens: "A pathological fear of chickens",
    },
    greedy: "These creatures love collecting anything that glitters. This makes them prone to bribery or distraction.",
    illusion: "At any time, these creatures can conjure an illusion that blends them in completely with their surroundings. The next time the creature performs an action, the illusion is broken.",
    immunity: {
        piercing: "These creatures are immune to all forms of piercing attacks, whether mundane or magical.",
    },
    impulsive: "These creatures are impatient and rarely think before they act. In combat they draw an extra initiative card and keep the [their Ferocity] lowest.",
    invisibility: "As an action, one of these creatures can become invisible except for its shadow. If an invisible creature performs an action that affects another creature, it immediately becomes visible and cannot become invisible again for one Stretch.",
    lifesaver: "No idea what this does. Look it up.",
    regeneration: "These creatures automatically heal 1d8 HP per turn in combat.",
    resistance: {
        bludgeoning: "These creatures take half damage from bludgeoning attacks",
        fire: "These creatures take half damage from fire.",
        mundane: "THese creatures take half damage from non-magical weapons and attacks.",
        piercing: "These creatures take half damage from piercing attacks",
        slashing: "These creatures take half damage from slashing attacks",
    },
    stench: "These creatures reek of rot and decay. This makes them easier to detect, but it also means that anyone who comes within 30 feet must make a CON roll to avoid becoming Dazed.",
    stride: "These creatures are capable of travelling at up to 35 mph over land, and never tire from travelling.",
    swarm: "These creatures fight together and some of their attacks are performed as a group. Such attacks still only use up the turn in the round for one fairy. Once half of the creatures have suffered damage, they flee, but will likely come back for revenge later.",
    trollSensitivity: "When in direct sunlight, trolls suffer 1d6 damage per round, and cannot regenerate. A troll that reaches 0 HP because of this turns to stone. Dense foliage, thick clouds, and even clothing are enough to avoid this effect.",
    vulnerability: {
        fire: "These creatures take double damage from fire, and will do everything they can to stop opponents using fire.",
    },
    wings: "These creatures fly around in erratic patterns. They always attack from the air and can only be attacked with ranged weapons or melee weapons with Reach.",
};

export const MONSTERS = [
    {
        name: "Centaur",
        ferocity: 2,
        movement: 12,
        size: "Large",
        armor: "",
        hp: 28,
        traits: [
            TRAITS.alcoholTolerance
        ],
        gear: "Short spear, war bow, quiver",
        attacks: [
            "The centaur kicks back at an opponent. The attack hurls the victim 10 feet and inflicts 1d6 points of bludgeoning damage. The victim lands prone.",
            "The creature thrusts its short spear at an opponent, inflicting 2D10 piercing damage. The attack can be parried.",
            "The centaur rears up and strikes with its hooves at two opponents within 5 feet of each other. Each victim suffers 2D6 bludgeoning damage.",
            "The creature uses its bow and quickly fires an arrow at an opponent within 100 feet, preferably a mage or another archer. The victim suffers 1D12 + 1d6 piercing damage.",
            "The creature lunges at an enemy with its full weight. The attack inflicts 2D10 bludgeoning damage and knocks the victim down.",
            "The centaur lets out a burst of deafening and mocking laughter. All enemies within 30 feet must make a WIL roll to not gain the Angry Condition. Anyone who is already Angry suffers another condition of their choice.",
        ]
    },
    {
        name: "Fairy",
        ferocity: 1,
        movement: 18,
        size: "Tiny",
        armor: "",
        hp: 6,
        traits: [
            TRAITS.swarm,
            TRAITS.wings,
            TRAITS.invisibility,
        ],
        gear: "",
        attacks: [
            "The fairies hurl insults and taunts at their enemies. Everyone within 100 feet must succeed with a WIL roll or gain the Angry condition, or a condition of their choice if they're already Angry.",
            "Several fairies swarm around an opponent and stab them with their needle-sharp daggers. The victim suffers 1d10 damage (armor has no effect) and gains the Dazed condition, or a condition of their choice if they're already Dazed.",
            "A fairy throws a fistful of glitter into the air which may blind anyone within 30 feet. Those affected must succeed at a Dodge roll or act as if in total darkness for 1D6 rounds.",
            "A fairy sneaks up behind an opponent and stabs them with the poisonous thorn of an enchanted rose. The victim is injected with a Paralyzing poison with Potency 12.",
            "One of the fairies blows an enchanted kiss at a victim, who must succeed at a Dodge roll or gain the Disheartened condition. Anyone who is already Disheartened gains another condition of their choice.",
            "A fairy fires an enchanted arrow at an enemy within 30 feet. The victim suffers 1D10 piercing damage and must make a WIL roll to resist Fear.",
        ]
    },
    {
        name: "Harpy",
        ferocity: 1,
        movement: 12,
        size: "Medium",
        armor: "",
        hp: 12,
        traits: [
            TRAITS.swarm,
            TRAITS.wings,
        ],
        gear: "",
        attacks: [
            "The harpies shower the PCs with terrible descriptions of what they will do to them. Everyone within 30 feet must make a WIL roll to resist Fear.",
            "The harpies flock together and attack the PC who wears the most metal. The attack inflicts 2D6 slashing damage. If damaged, the victim is also lifted into the air and dropped from a height of 1d3 x 10 feet (dealing an additional 1, 2, or 3d6 damage) on the harpies next turn.",
            "The harpies throw rocks and other junk from afar. Everyone within 30 feet suffers 1D6 bludgeoning damage.",
            "The harpies target an unfortunate PC and try to tear the victim's eyes out with their claws. The attack inflicts 2D6 piercing damage and the victim is blinded and acts as if in total darkness for one Stretch.",
            "The harpies split up and attack a number of player characters within 30 feet equal to the number of individual harpies. Each attack inflicts 1D8 slashing damage.",
            "The harpies open their cloacae and mouths and release a rain of vomit and excrement on the PCs. Everyone within 30 feet must gain a Condition. This attack can be Parried with a shield.",
        ]
    },
    {
        name: "Mermaid",
        ferocity: 1,
        movement: 12,
        size: "Medium",
        armor: "",
        hp: 16,
        traits: [
            TRAITS.lifesaver,
            TRAITS.aquatic,
        ],
        gear: "Spear, Harpoon, Trident, Net",
        attacks: [
            "The mermaid grabs a whale bone trident from a quiver on its back and throws it with full force at an enemy within 30 feet. The victim suffers 2D6 piercing damage.",
            "The mermaid thrusts its trident at an opponent. The attack inflicts 2D8 piercing damage and the victim is knocked down.",
            "The mermaid casts a net and swims with powerful tail strokes around all opponents within 15 feet. The victims must make an Dodge roll (not an action) to escape the net. Those who fail  are unable to move or perform actions that require body movement. Breaking free requires an action and a successful STR roll with a Bane. Others can help.",
            "The mermaid grabs a victim and pulls it into the water. The victim immediately begins to Drown and cannot move or perform actions that require body movement except trying to break free, which requires an action and a successful STR roll with a Bane. Others can help.",
            "The mermaid repeatedly slams its fishtail into the water and produces a powerful wave. All untethered objects and creatures within a 30 feet cone are pushed 1D6 hexes away and suffer an equal amount of bludgeoning damage.",
            "The mermaid creates a great whirlwind of water. All untethered objects and creatures up to human size within 10' of the mermaid are thrown 1D4 hexes and suffer an equal amount of bludgeoning damage.",
        ]
    },
    {
        name: "Minotaur",
        ferocity: 2,
        movement: 6,
        size: "Large",
        armor: "Natural (1)",
        hp: 32,
        traits: [],
        gear: "Clabbard Sword, Harpoon, Etc.",
        attacks: [
            "A furry fist hits a player character with full force. The attack inflicts 2D6 bludgeoning damage and leaves the victim Dazed, even if their armor prevents any damage.",
            "Using its powerful legs, the minotaur kicks the victim with its hooves. The force of the attack throws the victim 1D6 hexes away and inflicts the same amount of bludgeoning damage. The victim lands prone.",
            "The minotaur lowers its head and rushes toward one enemy, or two adjacent enemies, hoping to impale them with its sharp horns. Both victims suffer 2D8 piercing damage and are knocked prone.",
            "The beast swings its massive sword over its head and brings it down with full force. The attack inflicts 3d12 damage and can be Parried.",
            "The minotaur roars and sweeps its sword in a wide arc, hitting all adjacent enemies. The attack inflicts 2d12.",
            "The minotaur jumps high in the air and comes crashing down on an adventurer, who suffers 2D10 bludgeoning damage and is knocked down.",
        ]
    },
    {
        name: "Naiad",
        ferocity: 2,
        movement: 6,
        size: "Normal",
        armor: "",
        hp: 24,
        traits: [
            TRAITS.enchant,
            TRAITS.invisibility,
            TRAITS.aquatic,
            TRAITS.beautiful,
        ],
        gear: "",
        attacks: [
            "The naiad stretches out its long, strong arms and grabs a victim by the throat. The attack inflicts 1D10 bludgeoning damage and an additional 1D10 whenever it is the victim's turn. The strangled victim cannot move or perform actions that require body movement, except trying to break free, which requires an action and a successful STR roll with a Bane. Others can help.",
            "The naiad waves dismissively at a victim within 30 feet who suddenly realizes that their love for the creature will never be reciprocated! The victim must make a WIL roll with a Bane to resist Fear.",
            "The naiad claws at an opponent's eyes with its sharp fingernails. The attack inflicts 1D8 slashing damage, and the victim acts as if in total darkness for 1D3 rounds.",
            "The naiad grabs an opponent with its strong arms and pulls it into the water. The victim immediately begins to Drown and cannot move or perform actions that require body movement except trying to break free, which requires an action and a successful STR roll with a Bane. Others can help.",
            "With its sweet voice, the naiad seduces a victim within 30 feet. The victim must succeed with a WIL roll or immediately perform a movement and an action (must not require WP) of the naiad's(GM's) choosing. The victim also loses its turn in the round, if it has not already passed.",
            "The naiad summons a great wave from a water source within 30 feet. The area of effect is a 30 feet long cone emanating from the source. All untethered objects and creatures affected are pushed 1D6 hexes away from the source and suffer an equal amount of bludgeoning damage.",
        ]
    },
    {
        name: "Tree Kin",
        ferocity: 2,
        movement: 6,
        size: "Large",
        armor: 6,
        hp: 64,
        traits: [
            TRAITS.illusion,
            TRAITS.vulnerability.fire,
            TRAITS.resistance.piercing,
            TRAITS.resistance.bludgeoning,
            TRAITS.stride,
        ],
        gear: "",
        attacks: [
            "The tree kin speaks commanding words of power from ancient times. Everyone within 30 feet is shaken by its thunderous words and must make a WIL roll to resist fear.",
            "A swarm of small birds swoops down on all opponents within 30 feet. All victims suffer 1D8 damage and lose their next turn in the round, if it has not already passed.",
            "The creature shapes a long branch into a spear and thrusts it at a victim, inflicting 2D10 piercing damage. The attack can be parried.",
            "The tree kin gathers all its strength and slams its thickest branch into the head of a target, who suffers 2D10 bludgeoning damage and is knocked down.",
            "The monster grabs the victim and hurls it 1D8 hexes. The attack inflicts an equal amount of bludgeoning damage and the victim lands prone.",
            "The tree kin extends a long branch and wraps it around an opponent's neck. The attack inflicts 2D6 bludgeoning damage and an additional 2D6 whenever it is the victim's turn. The victim cannot move or perform actions that require body movement, except trying to break free which requires a STR roll with a Bane (action). Others can help.",
        ]
    },
    {
        name: "Troll",
        ferocity: 2,
        movement: 6,
        size: "Large",
        armor: 2,
        hp: 44,
        traits: [
            TRAITS.greedy,
            TRAITS.illusion,
            TRAITS.regeneration,
            TRAITS.stench,
            TRAITS.trollSensitivity,
        ],
        gear: "",
        attacks: [
            "The troll grabs a [suitable object] and brings it down on its opponents. Two victims adjacent to each other suffer 3D6 bludgeoning damage each and are knocked down.",
            "The troll blows its foul breath at an opponent within 10'. The victim becomes Sickly and must succeed with a CON roll (now with a Bane) or lose their turn in the round (if it has not already passed).",
            "With a gesture, the troll calls forth roots from the ground that snare a character within 30 feet. The victim becomes unable to move or perform actions that require movement. Breaking free requires a successful STR roll (counts as an action). Others can help.",
            "The troll flails wildly at all adjacent opponents. The attack inflicts 2D6 bludgeoning damage and knocks the victims down.",
            "With a [suitable object], the troll aims its strongest blow at an opponent. The victim suffers 4D6 bludgeoning damage and becomes Dazed.",
            "The troll thrusts its horns at an enemy. The victim suffers 2D10 bludgeoning damage and is knocked down.",
        ]
    },
    {
        name: "Basilisk",
        ferocity: 2,
        movement: 8,
        size: "Large",
        armor: 6,
        hp: 38,
        traits: [
            TRAITS.fear.chickens,
        ],
        gear: "",
        attacks: [
            "The basilisk slashes its terrible claws at two player characters within 10' of each other. Each attack inflicts 2D8 slashing damage.",
            "The beast thrusts its vile bird's head forward and pecks at a haracter with its razor-sharp beak. The attack inflicts 3D8 piercing damage.",
            "The basilisk lets out a cacophonous crow that makes the characters' ears bleed. Everyone within 30 feet must make a CON roll. On failure, a victim falls to the ground, becomes Dazed, and loses their turn in the round (if it has not already passed).",
            "The basilisk uses its snake-like tail as a whip in a sweeping attack against all adventurers within 10'. Each attack inflicts D10 bludgeoning damage, and anyone hit is knocked down.",
            "The basilisk spews a greenish-yellow cloud that reeks of poison and corrosive stomach acids. Everyone within 30 feet is affected by a lethal poison with Potency 15.",
            "A glow lights up in the basilisk's eyes as it turns its vicious bird's head towards the character who currently has the highest HP. If the victim can see (i.e., is not blind or blind-folded), they must make a WIL roll (not an action). On failure, their body turns to stone and the victim can no longer move or perform any actions whatsoever, but also cannot take damage. A petrified victim dies after 2D6 rounds, but the petrifaction can be reversed with a successful WIL roll. While still alive, the victim may roll WIL once per turn. The DISPEL spell can also undo the petrifaction, but only if the victim is still alive.",
        ]
    },
    {
        name: "Brooke Horse",
        ferocity: 2,
        movement: 12,
        size: "Large",
        armor: 0,
        hp: 34,
        traits: [
            "The brook horse can appear as an ordinary horse and is able to keep its instincts under control when hunting. It lures its victims into the water and tricks them into mounting it. If they do, the brook horse immediately gallops towards the deepest part of the water to throw the victim off and attack them by any means at its disposal. Seeing through a brook horse's facade requires a successful Beast Lore check.",
        ],
        gear: "",
        attacks: [
            "The brook horse kicks back at an opponent. The victim is thrown 1D8 hexes, lands prone, and takes an equal amount of bludgeoning damage.",
            "The brook horse bites an opponent with its sharp teeth. The victim suffers 2D10 slashing damage.",
            "The brook horse rears up and strikes with its hooves at two opponents within 10' of each other. Each victim suffers 2D6 bludgeoning damage and must make a WIL roll to resist Fear.",
            "The brook horse fixes its gaze on a character within 30 feet and focuses all its hatred on them. The victim must make a WIL roll with a Bane to resist Fear.",
            "The brook horse pulls an opponent into the deep and the victim immediately begins to Drown. The victim cannot move or perform actions that require movement, except trying to break free, which requires a STR roll with a Bane. Others can help.",
            "The brook horse lures an opponent to climb onto its back. Resisting requires a WIL roll with a Bane. On failure, the beast rides off with the victim at breakneck speed (up to twice its movement, i.e. 24 hexes), leaving the victim Exhausted and inflicting 1D6 damage (armor has no effect). This is repeated each round on the brook horse's turn, instead of rolling another monster attack, until the victim reaches zero HP or manages to jump off. On their turn, the victim can roll WIL again to throw themselves off the horse; on success, they take 2D6 bludgeoning damage from the fall (armor has no effect).",
        ]
    },
    {
        name: "Calydon",
        ferocity: 2,
        movement: 8,
        size: "Large",
        armor: 0,
        hp: 52,
        traits: [
            TRAITS.resistance.fire,
        ],
        gear: "",
        attacks: [
            "The calydon charges an opponent and rams them hard. The victim is thrown 1D6 hexes backwards, takes an equal amount of bludgeoning damage, and is knocked down.",
            "The calydon thrusts its tusks at an opponent, inflicting 1D12 piercing damage.",
            "The calydon rears up and kicks an opponent with its hooves. The victim suffers 2D8 bludgeoning damage and is knocked down.",
            "The calydon catches an opponent with its tusks and hurls the victim 1D4 hexes. The victim suffers an equal amount of bludgeoning damage (armor has no effect) and becomes Dazed.",
            "The calydon lets out a grunt filled with hatred and malice. Everyone within 30 feet must make a WIL roll to resist Fear.",
            "The calydon takes a deep breath and blasts its enemies with a 20' cone of fire. Anyone hit by the flames suffer 2D10 damage. Armor has no effect.",
        ]
    },
    {
        name: "Chimera",
        ferocity: 3,
        movement: 8,
        size: "Large",
        armor: 0,
        hp: 42,
        traits: [
            "Having three heads, a chimera is difficult to surprise. Attempts to use Stealth around a chimera are rolled with a Bane.",
        ],
        gear: "",
        attacks: [
            "The chimera lunges at an opponent, tearing at them with its sharp claws. The attack inflicts 2D8 slashing damage and knocks the victim down.",
            "The lion's head opens its great jaws and bites an opponent with its big, sharp fangs. The attack inflicts 2D10 slashing damage.",
            "The chimera jumps up to an opponent and butts the victim with its goat head. The attack deals 2D6 bludgeoning damage and leaves the victim Dazed.",
            "The snake head lashes out at an opponent within 10' and delivers a venomous bite, inflicting 1D8 piercing damage. If the victim takes damage, they are also injected with a Lethal poison with Potency 15.",
            "The chimera pounces on an opponent and directs all its attacks at the unfortunate victim. The attack deals 2D10 slashing damage, 2D6 bludgeoning damage, and 1D8 piercing damage. Armor protects against each of these. If the piercing damage penetrates the armor, the victim is injected with a lethal poison with Potency 15.",
            "The chimera roars, bleats, and hisses in a deafening cacophony. Everyone within 30 feet must make a WIL roll to resist Fear.",
        ]
    },
    {
        name: "Ooze",
        ferocity: 2,
        movement: 4,
        size: "Large",
        armor: 0,
        hp: 64,
        traits: [
            TRAITS.resistance.mundane,
            TRAITS.immunity.piercing,
            TRAITS.vulnerability.fire,
            "Oozes are corrosive. Anyone who touches or is touched by the ooze is exposed to a Paralytic poison, Potency 9.",
        ],
        gear: "",
        attacks: [
            "The ooze forms tentacles that strike at all adjacent characters. The victims suffer 1D10 bludgeoning damage and risk being exposed to the ooze's corrosive poison (see above).",
            "Twisted faces appear on the surface of the shapeless body mass: floating by, dissolving, or morphing into something else, in a mocking imitation of intelligent life. All opponents within 30 feet must make a WIL roll to resist Fear.",
            "The slimy creature launches a long tentacle at an enemy within 20', snatching a weapon from the victim's hand. The weapon is absorbed by the ooze's body and can only be recovered by killing the beast.",
            "From the depths of its gelatinous being, the ooze spits a disgusting ball of slime at an opponent within 30 feet. The victim suffers 1D8 bludgeoning damage and risks being exposed to the monster's corrosive poison.",
            "The ooze gathers its strength and emits a stinking cloud of poison that affects everyone within 30 feet. The victims become Dazed and are exposed to a paralyzing poison with potency 12.",
            "The monster sends out tentacles towards an opponent, enveloping their body and pulling them into its slimy interior. Once inside the ooze, the victim is immediately exposed to its corrosive poison (see above) and suffers 1D6 damage (armor has no effect). The victim takes an additional 1D6 damage per turn but can continue to attack the ooze from within. The victim gets out when the ooze is dead.",
        ]
    },
    {
        name: "Giant Spider",
        ferocity: 2,
        movement: 16,
        size: "Normal",
        armor: 0,
        hp: 36,
        traits: [
            "A single strand of giant spider web is as thick as a dwarven thumb. It can only be destroyed with slashing weapons, fire, or magic. Each strand has durability 9. 2d4 strands must be cut in a web to allow passage of a medium-sized creature.",
        ],
        gear: "",
        attacks: [
            "The spider's serrated mandibles swish through the air like scimitars. The attack inflicts 2D8 slashing damage on an opponent.",
            "The famished spider lunges at its victims, frantically attacking with its multitude of hairy, barbed legs. All adjacent opponents suffer 1D8 piercing damage.",
            "The monstrous arachnid stares at its victims with a terrifying multitude of eyes. Everyone within 30 feet must make a WIL roll to resist Fear.",
            "The eight-legged horror raises its rear end and attacks a victim with a poisonous stinger that shoots out of its repulsive body. The attack inflicts 1D10 piercing damage, and a victim who sustains at least 1 point of damage is also injected with a paralyzing poison with potency 16. The attack can be parried.",
            "The spider fixes its numerous eyes on the opponent with the highest STR. The next moment it spits sticky spider web at the victim, who must make an Dodge roll (not an action). On failure, the victim is caught in the web and unable to move or perform actions that require movement. It takes a successful STR roll with a Bane (action) to break free. Others can help.",
            "With a great leap, the giant spider launches its massive body at an opponent. The attack inflicts 2D6 bludgeoning damage and knocks the victim down.",
        ]
    },
];
