const SCHOOLS = {
    general: "General",
    animism: "Animism",
    elementalism: "Elementalism",
    mentalism: "Mentalism",
    abjuration: "Abjuration",
    evocation: "Evocation",
    conjuration: "Conjuration",
    transmutation: "Transmutation",
    illusion: "Illusion",
    witchcraft: "Witchcraft",
};

const TYPES = {
    arcane: "Arcane",
    divine: "Divine",
    both: "Both",
};

const NA = "N/A";

const REQUIREMENTS = {
    word: "Word",
    gesture: "Gesture",
    component: "Component",
    wordAndGesture: "Word, Gesture",
    gestureAndComponent: "Gesture, Component",
    allThree: "Word, Gesture, Component",
};

const RANGES = {
    personal: "Personal",
    touch: "Touch",
    close: "30 feet/6 hexes",
    medium: "60 feet/12 hexes",
    long: "100 feet/20 hexes",
    aoe: "Area of Effect",
    sphere: "Sphere",
    cone: "Cone",
};

const DURATIONS = {
    instant: "Instant",
    round: "Round",
    stretch: "Stretch",
    shift: "Shift",
    concentration: "Concentration",
    permanent: "Permanent",
};

const CASTING_TIMES = {
    action: "Action",
    reaction: "Reaction",
    stretch: "Stretch",
    shift: "Shift",
};

export const SPELLS = [
    {
        rank: 0,
        name: "Fetch",
        type: TYPES.both,
        school: SCHOOLS.general,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.medium,
        requirements: REQUIREMENTS.allThree,
        duration: DURATIONS.round,
        description: "You make a loose object (no heavier than 1 bulk or 1 grip) within 30 feet float to you.",
    },
    {
        rank: 0,
        name: "Flick",
        type: TYPES.both,
        school: SCHOOLS.general,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.close,
        requirements: NA,
        duration: DURATIONS.instant,
        description: "You give an object or creature within 30 feet a magical flick. The 'attack' inflicts 1 point of damage and can, for example, shatter glass.",
    },
    {
        rank: 0,
        name: "Light",
        type: TYPES.both,
        school: SCHOOLS.general,
        prerequisite: NA,
        range: RANGES.touch,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.shift,
        description: "You create a bright light that shines from a focus of your choice. It illuminates a 30-foot radius around your focus and lasts for one Shift of time. The light goes out if you react zero HP.",
    },
    {
        rank: 0,
        name: "Open/Close",
        type: TYPES.arcane,
        school: SCHOOLS.general,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.close,
        requirements: NA,
        duration: DURATIONS.instant,
        description: "You open or close an unlocked, freely-moving door within 30 feet that you can see.",
    },
    {
        rank: 0,
        name: "Repair Clothes",
        type: TYPES.arcane,
        school: SCHOOLS.general,
        prerequisite: NA,
        castingTime: CASTING_TIMES.instant,
        range: RANGES.close,
        requirements: NA,
        duration: DURATIONS.instant,
        description: "Clothes belonging to you or someone else are instantly repaired and cleaned.",
    },
    {
        rank: 0,
        name: "Sense Magic",
        type: TYPES.arcane,
        school: SCHOOLS.general,
        prerequisite: NA,
        castingTime: CASTING_TIMES.instant,
        range: RANGES.touch,
        requirements: NA,
        duration: DURATIONS.instant,
        description: "You can sense whether the place your are in, or an item you are holding, is affected by magic - and if so, what kind of magic.",
    },
    {
        rank: 1,
        name: "Alarm",
        type: TYPES.arcane,
        school: SCHOOLS.general,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.gesture,
        duration: "Shift. Increases to a week at PL 2 and a year at PL 3.",
        description: "You inscribe an invisible rune upon an object and set a trigger condition. The object may be a door, a floor tile, an urn, or any other isolated, non-organic object. The trigger condition could be someone opening the door, stepping on the floor tile, or touching the urn. When the condition is met, you immediately become aware of it, no matter where you are.",
    },
    {
        rank: 1,
        name: "Dispel",
        type: TYPES.both,
        school: SCHOOLS.general,
        prerequisite: NA,
        range: RANGES.close,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.instant,
        description: "You cancel an ongoing spell of lower or equal PL (including PROTECTOR). The spell can also be used to end other magical effects, if the GM allows it. DISPEL cannot be used against powerful rituals such as NEXUS, PERMANENCE, and FAMILIAR. Canceling such magic requires the COUNTER RITUAL spell.",
    },
    {
        rank: 0,
        name: "Bird Song",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.aoe,
        castingTime: CASTING_TIMES.action,
        requirements: REQUIREMENTS.word,
        duration: DURATIONS.stretch,
        description: "You are surrounded by lovely birdsong for one Stretch of time. The birds give you a Boon to Perception. This cantrip only works outdoors.",
    },
    {
        rank: 0,
        name: "Clean",
        type: TYPES.arcane,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.aoe,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.instant,
        description: "The room you are in is cleaned. All dust and dirt disappear, and the room is put in order.",
    },
    {
        rank: 0,
        name: "Cook Food",
        type: TYPES.both,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.touch,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.instant,
        description: "You automatically succceed at cooking food without a Cooking check, and it happens instantly (as part of the casting action).",
    },
    {
        rank: 0,
        name: "Floral Trail",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.touch,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.shift,
        description: "Beautiful flowers sprout where you walk. The flowers whither after a Shift.",
    },
    {
        rank: 0,
        name: "Hairstyle",
        type: TYPES.arcane,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.touch,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.shift,
        description: "You change the color, length, and style of your hair as you see fit. In some situations this can give you a Boon to Bluffing and Persuasion checks.",
    },
    {
        rank: 1,
        name: "Animal Whisperer",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.personal,
        castingTime: CASTING_TIMES.stretch,
        requirements: REQUIREMENTS.word,
        duration: DURATIONS.instant,
        description: "This spell lets you talk to a bird or mammal. You can ask a number of questions equal to the PL. Animals can tell you what they have seen, heard, or smelled - but they do not perceive the world as humanoids do, and their answers are hard to interpret. The main advantage is that they never lie.",
    },
    {
        rank: 1,
        name: "Banish",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        range: RANGES.close,
        castingTime: CASTING_TIMES.action,
        requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
        duration: DURATIONS.instant,
        description: "Demons and undead rising from their graves are a violation of the natural order and must be stopped. This spell inflicts 2d8 damage on such a being. Each additional PL increases the damage by 1d8. Armor and natural armor have no effect, and the spell cannot be dodged or parried.",
    },
    {
        rank: 1,
        name: "Ensnaring Roots",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.close,
        requirements: REQUIREMENTS.gestureAndComponent,
        duration: DURATIONS.shift,
        description: "The victim is ensnared by roots and branches and is unable to move. Breaking free requires a Dodge check - with a Boon at PL 1, normally at PL 2, and with a Bane at PL 3. Each attempt counts as an action in combat. Only one attempt is allowed per round, but others can help. The spell does not work on Monsters.",
    },
    {
        rank: 1,
        name: "Lightning Flash",
        type: TYPES.both,
        school: SCHOOLS.animism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.medium,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.instant,
        description: "You call down a flash of lightning from the sky. If the spell is cast successfully, the target takes 2d6 damage. The lightning flash continues to another random target adjacent to the initial target, inflicting 2d4 damage. Each PL beyond the first increases the number of dice rolled for damage by one. Metal armor has no effect but the spell can be Dodged or Parried as a ranged attack, and if this is successfully done, no further target is hit. Indoors, the WP cost to cast the spell is doubled.",
    },
    {
        rank: 1,
        name: "Nourish",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.instant,
        description: "You can get all the necessary nutrients and hydration by sprouting threadlike roots from your hands and feet and burrowing them into the earth. This process takes a Stretch to complete and fulfills your need for food and water for a full day. The required PL depends on the environment - PL 1 in forests and fertile wilderness; PL 2 in towns, villages, or vegetated mountains; and PL 3 in barren mountains or caverns.",
    },
    {
        rank: 1,
        name: "Treat Wound",
        type: TYPES.divine,
        school: SCHOOLS.animism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.word,
        duration: DURATIONS.instant,
        description: "You heal a living creature for 2d6 HP. You can use the spell on yourself. For each PL beyond the first, the spell heals an additional 1d6 HP.",
    },
    {
        rank: 0,
        name: "Heat/Chill",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.aoe,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.shift,
        description: "The area within 30 feet of you becomes pleasantly warm or cold. The effect protects against extreme temperatures for one Shift of time.",
    },
    {
        rank: 0,
        name: "Ignite",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.close,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "You light or extinguish a candle, torch, or lantern within 30 feet.",
    },
    {
        rank: 0,
        name: "Puff of Smoke",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "An impressive puff of smoke erupts in front of you. Very popular for dramatic entrances, and can give you a Boon to Stealth checks in certain situations as determined by the GM.",
    },
    {
        rank: 1,
        name: "Fireball",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.medium,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "The spell sends a fireball from your hand or holy symbol at the target. The fireball can be Dodged or Parried as a ranged attack. The fireball inflicts 2d6 damage on a hit and sets fire to flammable objects. Each PL beyond the first increases the damage by 1d6 or creates another fireball that hits another target within range.",
    },
    {
        rank: 1,
        name: "Frost",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.aoe,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "You drastically lower the temperature around you in a 5-foot radius. All natural fires in the area are extinguished and all living creatures lose 1d6 HP anc 1d6 WP when the spell is cast, and become cold as per the Extreme Temperature rules - they cannot heal HP or WP until they get warm. Humanoids (not Monsters) in the area of effect when the spell is cast are also frozen in place and can neither move nor perform actions (not even reactions). On each turn, a frozen victim can make a STR roll (not an action) to break free. Each additional PL increases the ranged by 5 feet. Any water in the area of effect immediately freezes. In a river this creates an ice floe that you can walk on or use as a raft.",
    },
    {
        rank: 1,
        name: "Gust of Wind",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: "30-foot cone",
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "The spell summons a great gust of wind. All untethered objects and creatures up to (and including) human size in the area of effect (a 30-foot cone) are pushed 1d4 hexes away from you and suffer the same amount of bludgeoning damage. Against a swarm the spell deals 2d6 damage. Each additional PL increases the number of dice by one. The spell has no effect on Monsters that are Large or Huge.",
    },
    {
        rank: 1,
        name: "Pillar",
        type: TYPES.arcane,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.close,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.shift,
        description: "The spell raises a pillar, 10 feet high and 3 feet wide, from the ground or a stone floor. If someone is standing in that spot, the victim must make an Acrobatics check (not an action) to avoid falling off the pillar (falling would cause 1d6 bludgeoning damage). If the pillar is created under a lower ceiling and the Acrobatics check fails, the victim takes 2d6 bludgeoning damage instead. For each additional PL, the height of the pillar increases by 10 feet, which can increases the falling damage to anyone who falls off. It isn't clear how Large or larger beings are affected by this spell.",
    },
    {
        rank: 1,
        name: "Shatter",
        type: TYPES.divine,
        school: SCHOOLS.elementalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.word,
        duration: DURATIONS.instant,
        description: "By breaking the invisible bond that holds physical matter together, you can shatter physical objects. With this spell you inflict 2d10 damage on an inanimate and non-magical item. Any armor rating has no effect. Each PL beyond the first increases the damage by 1d10.",
    },
    {
        rank: 0,
        name: "Double Tongue",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.instant,
        description: "You say something out loud, but one person nearby hears something completely different - your true message. This is used to let a companion know it is time to flee, fight, or simply keep quiet.",
    },
    {
        rank: 0,
        name: "Embellish",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.shift,
        description: "You enhance reality with more vibrant colors, purer sounds, or richer flavors and scents. The effect covers a room-sized area for a Stretch of time and will not fool anyone who does not want to be fooled.",
    },
    {
        rank: 0,
        name: "Phantasm",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "You conjure false objects and glowing orbs out of thin air, purely to entertain and impress. You can use this effect to gain a Boon on Bluff or Performance checks.",
    },
    {
        rank: 0,
        name: "Shadow Play",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.aoe,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "You breathe life into shadows, making them dance, take on ominous shapes, or even crawl across your skin to unsettle and impress onlookers. The effect is so distracting that anyone watching suffers a Bane on Perception checks.",
    },
    {
        rank: 1,
        name: "Apparition",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.long,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.concentration,
        description: "You create an apparition of a creature up to human size, within range. Anyone within sight perceives the apparition as real, but it is strictly visual and cannot speak or make any other sound. Seeing through the apparition requires a Perception check (not an action) - made with a Boon at PL 1, normally at PL 2, and with a Bane at PL 3. Anyone who fails this check must act as if apparition were real. A new roll may be attempted every round. The apparition immediately dissipates (for everyone) if anyone tries to touch it. This spell has no effect on Monsters.",
    },
    {
        rank: 1,
        name: "Confusion",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.medium,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.concentration,
        description: "You overwhelm a target's mind with a mental kaleidoscope of intense sensory impressions. Casting this spell requires an opposed roll against the target's WIL. You roll with a Bane at PL 1, normally at PL 2, and with a Boon at PL 3. If you succeed, the victim cannot perform reactions and must act randomly on their turn. Roll a 1d4 to determine the victim's behavior: 1: looks confused and does nothing else; 2: attacks a random creature within range; 3: attacks themselves (roll for hit and damage as usual); 4: dashes away in a random direction (if the victim hits a wall, they fall prone and take 1d6 Bludgeoning damage). A new opposed WIL check is made on each of the victim's subsequent turns. The effect ends if you break concentration or lose an opposed roll. This spell has no effect on Monsters or undead.",
    },
    {
        rank: 1,
        name: "Long Shadows",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.close,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.stretch,
        description: `All naturally occurring shadows within range deepen, granting a Boon on Stealth checks. If there are no natural shadows, the spell has no effect. The range increases to ${RANGES.medium} at PL 2, and to ${RANGES.long} at PL 3.`,
    },
    {
        rank: 1,
        name: "Mind Mask",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.stretch,
        description: "You hide your mind behind a veil of illusions. Your physical appearance does not change, but spells like DIVINATION and MAGIC SEAL can be tricked into believing you are a different creature or type of creature. This effect also applies to traps, locations, or Monsters that distinguish between specific creatures or types of creatures. MIND MASK also imposes a Bane on any spells affecting your mind, such as TELEPATHY and DOMINATE. At PL 2, you may extend the effect to one additional person besides yourself. At PL 3, you may affect two additional people. You cann cast MIND MASK again while the spell is active.",
    },
    {
        rank: 1,
        name: "Send Dream",
        type: TYPES.arcane,
        school: SCHOOLS.illusion,
        prerequisite: NA,
        castingTime: CASTING_TIMES.stretch,
        range: "3,280 feet",
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.concentration,
        description: "You project a dream into the mind of a person you have met before. This ritual can only be performed while the target is asleep. You can useit to deliver a message or create a nightmare. In the latter case, the sleep does not count as rest and the target cannot take a long rest until a full day has passed. However, the victim can resist the effect with a WIL check - made with a Boon at PL 1, normally at PL 2, and with a Bane at PL 3.",
    },
    {
        rank: 0,
        name: "Lock/Unlock",
        type: TYPES.arcane,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.instant,
        description: "Your touch locks or unlocks a non-magical lock.",
    },
    {
        rank: 0,
        name: "Magic Stool",
        type: TYPES.both,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.gesture,
        duration: DURATIONS.instant,
        description: "You create a round surface, roughly 2 feet in diameter and height, which you can sit on or put things on. The effect lasts until you leave.",
    },
    {
        rank: 0,
        name: "Slow Fall",
        type: TYPES.both,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.reaction,
        range: RANGES.personal,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "You slow your fall and land as light as a feather, no matter the height.",
    },
    {
        rank: 1,
        name: "Farsight",
        type: TYPES.divine,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: "1 kilometer",
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.concentration,
        description: "The spell lets you see and hear what is happening in a place up to one kilometer away, as if you were there in person. You must either have the place in sight or have visited it previously. Each additional PL increases the range tenfold - 10 km at PL 2 and 100 km at PL 3. The spell cannot be used to peer into other dimensions.",
    },
    {
        rank: 1,
        name: "Levitate",
        type: TYPES.divine,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "You levitate yourself or another person or object of up to human size and let it float up to 15 feet in any direction, after which it lands gently or drops to the ground (you decide). Each additional PL lets you levitate the target another 5 feet or levitate an additional person or object. If you try to levitate an unwilling creature, you get a Bane to the casting check.",
    },
    {
        rank: 1,
        name: "Longstrider",
        type: TYPES.divine,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "The target's movement rating is doubled for the duration of the effect. You can cast the spell on yourself. Each additional PL lets you cast the spell on another person.",
    },
    {
        rank: 1,
        name: "Power Fist",
        type: TYPES.divine,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "The damage of your unarmed attacks increases by 1d6 per PL.",
    },
    {
        rank: 1,
        name: "Stone Skin",
        type: TYPES.divine,
        school: SCHOOLS.mentalism,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: "Word, gesture, ingredient (stone)",
        duration: DURATIONS.stretch,
        description: "The target's skin turns hard and gray, and gains armor rating 4. Each PL beyond the first increases the armor rating by an additional 2. If the target is wearing armor, only the highest armor rating counts. You can cast this spell on yourself.",
    },
    {
        rank: 0,
        name: "Broom Sweep",
        type: TYPES.arcane,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "You enchant a broom to clean the room you are currently in. Dust and dirt vanish, and items are neatly tidied.",
    },
    {
        rank: 0,
        name: "Itch",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.medium,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "You trigger a localized itch on a person within 60 feet that you can see. The itching is irritating but harmless and subsides after a Stretch of time.",
    },
    {
        rank: 0,
        name: "Read Stars",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.stretch,
        range: RANGES.touch,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "You can divine another person's future in the stars. This takes a Stretch of time (the casting time) and grants a Boon on a Bluff or Persuasion check against that person.",
    },
    {
        rank: 1,
        name: "Animal Sense",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.long,
        requirements: REQUIREMENTS.word,
        duration: DURATIONS.round,
        description: "You can project your consciousness into a common animal within range, seizing control of its body. PL 2 increases the duration to one Stretch, and PL 3 to one Shift. You cannot compel the animal to act against its basic nature, nor will it fight on your command. While in animal form, you cannot speak or use your own skills - the animal's stats are used instead. Your own body remains in a defenseless trance while you control the animal. If the animal is killed while the spell is active, you take damage equal to the PL.",
    },
    {
        rank: 1,
        name: "Augury",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.stretch,
        range: RANGES.personal,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.instant,
        description: "You divine the future. You may ask a number of questions equal to the PL regarding the coming day. The GM answers each question truthfully with yes, no, or uncertain.",
    },
    {
        rank: 1,
        name: "Helper",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.touch,
        requirements: "Word, Components",
        duration: DURATIONS.stretch,
        description: "You fashion a helper from simple materials such as sticks, moss, and candles. This knee-high creature obeys your commands for the duration of the spell, performing simple tasks that do not require skill rolls. It must remain within 150 feet of you. PL 2 increases the duration to one Shift, and PL 3 to one day. You can only have one helper at a time. When the spell ends, the creature dissolves with pitiful squeaks, leaving behind a small pile of debris only fit for lighting a fire.",
    },
    {
        rank: 1,
        name: "Protective Aura",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.personal,
        requirements: REQUIREMENTS.word,
        duration: DURATIONS.round,
        description: "Any living creature wishing to attack you must acceed at a WIL check (not an action). On failure, they must choose another target or simply refrain from attacking. PL 2 increases the duration to a Stretch, and PL 3 to a Shift. Demons, Monsters, and undead are unaffected by the aura.",
    },
    {
        rank: 1,
        name: "Witch Mark",
        type: TYPES.divine,
        school: SCHOOLS.witchcraft,
        prerequisite: NA,
        castingTime: CASTING_TIMES.action,
        range: RANGES.medium,
        requirements: REQUIREMENTS.wordAndGesture,
        duration: DURATIONS.stretch,
        description: "You mark a creature with an invisible witch's mark, imposing a Bane on all the target's WIL rolls to resist Fear and magical effects. PL 2 increases the duration to a Shift, and PL 3 to a day.",
    },
];


// export const SPELLS = [
//     {
//         rank: 0,
//         name: "Summon Animal Companion",
//         type: TYPES.both,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.allThree,
//         duration: DURATIONS.concentration,
//         description: "You persuade a small animal to aid you, providing you with a Boon to Perception checks.",
//     },
//     {
//         rank: 0,
//         name: "Prestidigitation",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.personal,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "The room you are in is cleaned. Dust and dirt are swept away, spilled liquids are mopped up, and upset furniture is righted.",
//     },
//     {
//         rank: 0,
//         name: "Cook Food",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.personal,
//         requirements: REQUIREMENTS.allThree,
//         duration: DURATIONS.instant,
//         description: "You turn raw ingredients into a delicious meal with a single action.",
//     },
//     {
//         rank: 0,
//         name: "Floral Trail",
//         type: TYPES.divine,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.personal,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.shift,
//         description: "Beautiful flowers sprout where you walk, and wither after a Shift has passed.",
//     },
//     {
//         rank: 1,
//         name: "Speak With Animals",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.stretch,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.word,
//         duration: DURATIONS.instant,
//         description: "This spell lets you talk to a bird or mammal. You can ask a number of questions equal to the power level. The animal can tell you what they have seen, heard, or smelled - but they do not perceive the world as humanoids do, and their answers are difficult to interpret. The main advantage is that they seldom have a reason to lie.",
//     },
//     {
//         rank: 1,
//         name: "Smite Undead",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "Undead rising from their graves are a violation of the natural order and must be stopped. This spell inflicts 2d8 damage on such a being, plus 1d8 for each additional power level. Armor and natural armor have no effect, and this spell cannot be dodged or parried.",
//     },
//     {
//         rank: 1,
//         name: "Ensnaring Roots",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.gestureAndComponent,
//         duration: DURATIONS.shift,
//         description: "The target is ensnared by roots and branches and is unable to move. Breaking free requires a Dodge roll. This roll receives a Boon at power level 1, is normal at power level 2, and with a Bane at power level 3. Attempting to escape is an action, and only be attempted once per round, but others can help. This spell does not work on Monsters, and does not work if there are no nearby plants.",
//     },
//     {
//         rank: 1,
//         name: "Lightning Flash",
//         type: TYPES.both,
//         school: SCHOOLS.animism,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.gesture,
//         duration: DURATIONS.instant,
//         description: "You call down a flash of lightning from the sky. If this spell is successfully cast, the target takes 2d6 damage. The lightning flash continues to a random, adjacent target, inflicting 2d4 damage. Each power level beyond the first increases the number of damage dice rolled by 1. Metal armor offers no protection against this spell, but other armors do. This spell can be dodged or parried as a ranged attack, and if the first target does, a second target is not struck. Casting this spell indoors doubles the WP cost.",
//     },
//     {
//         rank: 1,
//         name: "Treat Wound",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.touch,
//         requirements: REQUIREMENTS.word,
//         duration: DURATIONS.instant,
//         description: "You heal a living creature for 2d6 HP. You can use this spell on yourself. For each power level beyond the first, the spell heals an additional 1d6 HP.",
//     },
//     {
//         rank: 2,
//         name: "Engulfing Forest",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: "Ensnaring Roots",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.personal,
//         requirements: REQUIREMENTS.gestureAndComponent,
//         duration: DURATIONS.shift,
//         description: "You call upon the spirits of the forest, who quickly fill the area around you with thickets of thorns and roots protruding from the soil. A circle with a 15 foot radius around you becomes difficult terrain, and everyone in the AoE (other than yourself) is ensnared, unable to move. Breaking free requires a Dodge roll. This roll receives a Boon at PL 1, is normal at PL 2, and receives a Bane at PL 3. Attempting to escape is an action and can only be attempted once per round. Other people, who are not ensnared, can help. This spell fails if there are no nearby plants.",
//     },
//     {
//         rank: 2,
//         name: "Lightning Bolt",
//         type: TYPES.both,
//         school: SCHOOLS.animism,
//         prerequisite: "Lightning Flash",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.gesture,
//         duration: DURATIONS.instant,
//         description: "You call down a great bolt of lightning on a target, who suffers 2d8 damage. This bolt strikes a random target within 10 feet of the first, dealing 2d6 damage. The bolt then strikes a target within 10 feet of the second target, and deals 2d4 damage. Each PL beyond the first increases the number of damage dice rolled by one. Metal armor offers no protection against this spell, but other armors do. This spell can be dodged or parried as a ranged attack, and if the first target does, a second target is not struck. Casting this spell indoors doubles the WP cost.",
//     },
//     {
//         rank: 2,
//         name: "Healing",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: "Treat Wound",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.touch,
//         requirements: REQUIREMENTS.word,
//         duration: DURATIONS.instant,
//         description: "You heal a living creature for 2d8 HP and one non-permanent severe injury. You can use this spell on yourself. For each PL beyond the first, the spell heals an additional 1d8 HP.",
//     },
//     {
//         rank: 2,
//         name: "Purge Undead",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: "Smite Undead",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "You exorcise an undead creature, dealing 2d10 damage to it. Each PL increases the damage by 1d10. Armor and natural armor have no effect, and this spell can neither be dodged nor parried.",
//     },
//     {
//         rank: 2,
//         name: "Sleep",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: "Treat Wound",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.touch,
//         requirements: REQUIREMENTS.word,
//         duration: DURATIONS.instant,
//         description: "The target of this spell must succed at a WIL check or fall into a deep sleep for one Stretch. If the target succeeds at their roll, they still gain the Dazed condition. The target gains a Boon on their roll at PL 1, rolls normally at PL 2, and receives a Bane at PL 3. The sleep caused by this spell is very deep, and can only be disrupted by damage. This spell has no effect on the undead or on Monsters.",
//     },
//     {
//         rank: 3,
//         name: "Restoration",
//         type: TYPES.divine,
//         school: SCHOOLS.animism,
//         prerequisite: "Healing",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.touch,
//         requirements: REQUIREMENTS.word,
//         duration: DURATIONS.instant,
//         description: "You heal a living creature for 2d10 HP and any one severe injury. You can use this spell on yourself. Each PL beyond the first heals an additional 1d10 HP.",
//     },
//     {
//         rank: 4,
//         name: "Thunderblast",
//         type: TYPES.both,
//         school: SCHOOLS.animism,
//         prerequisite: "Lightning Bolt",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.medium,
//         requirements: REQUIREMENTS.gesture,
//         duration: DURATIONS.instant,
//         description: "You call down a mighty thunderstroke on a target, who suffers 2d10 damage. The thunderstroke continues to up to three random targets within 10 feet of each other. These targets take 2d8, 2d6, and 2d4 damage respectively. Each PL beyond the first increases the number of damage dice rolled by one. Metal armor offers no protection against this spell, but other armors do. This spell can be dodged or parried as a ranged attack, and if the first target does, a second target is not struck. Casting this spell indoors doubles the WP cost.",
//     },
//     {
//         rank: 5,
//         name: "Resurrection",
//         type: TYPES.both,
//         school: SCHOOLS.animism,
//         prerequisite: "Restoration",
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.touch,
//         requirements: REQUIREMENTS.allThree,
//         duration: DURATIONS.permanent,
//         description: "You can channel divine power to resurrect a dead person - not as an undead creature, but truly alive. This costs the cleric one point of WIL permanently (and reduces their maximum WP by 1). The more time that has passed since the target died, the more difficult resurrection is. A person who died within one Shift requires PL 1, within 6 Shifts requires PL 2, and within a week requires PL 3. If more than a week has passed, the body is too decomposed to be resurrected. Only one attempt can be made per corpse; if the spell fails, the person is permanently dead. A resurrected character loses 1d3 skill levels in all CHA-based skills (to a minimum of 3).",
//     },
//     {
//         rank: 0,
//         name: "Mage Hand",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: NA,
//         duration: DURATIONS.instant,
//         description: "A loose, Tiny object you can see within 30 feet floats to you.",
//     },
//     {
//         rank: 0,
//         name: "Flick",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: NA,
//         duration: DURATIONS.instant,
//         description: "You give an object or creature within 30 feet a magical flick. The flick deals 1 point of damage and can, for example, shatter glass.",
//     },
//     {
//         rank: 0,
//         name: "Open/Close",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.action,
//         range: RANGES.close,
//         requirements: NA,
//         duration: DURATIONS.instant,
//         description: "You open or close an unlocked, freely moving door within 30 feet.",
//     },
//     {
//         rank: 0,
//         name: "Mending",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.instant,
//         range: RANGES.touch,
//         requirements: NA,
//         duration: DURATIONS.instant,
//         description: "Clothes belonging to you or someone else are instantly repaired and cleaned.",
//     },
//     {
//         rank: 0,
//         name: "Detect Magic",
//         type: TYPES.both,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         castingTime: CASTING_TIMES.instant,
//         range: RANGES.close,
//         requirements: NA,
//         duration: DURATIONS.concentration,
//         description: "Clothes belonging to you or someone else within 30 feet are instantly repaired and cleaned.",
//     },
//     {
//         rank: 1,
//         name: "Light",
//         type: TYPES.both,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.action,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
//         duration: DURATIONS.shift,
//         description: "You create a light that shines from a focus of your choice. It illuminates a 10-foot radius per power level; light within that radius is at a normal level.",
//     },
//     {
//         rank: 1,
//         name: "Dispel",
//         type: TYPES.both,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         range: RANGES.close,
//         castingTime: CASTING_TIMES.action,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
//         duration: DURATIONS.instant,
//         description: "You cancel an ongoing spell of lower or equal power level. If the target spell is not one that you cast, you have a Bane on your casting check.",
//     },
//     {
//         rank: 1,
//         name: "Protection From Magic",
//         type: TYPES.both,
//         school: SCHOOLS.general,
//         prerequisite: NA,
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.stretch,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}, ${REQUIREMENTS.component}`,
//         duration: DURATIONS.shift,
//         description: "You protect a person or person-sized object from magic. You may target yourself. The power level of all spells cast at the target is reduced by the power level used to cast Protection. You can also use this spell to protect against the magical attacks of Monsters. In that case, each power level reduces the number of dice rolled for damage by 1. The component is runes inscribed on the target.",
//     },
//     {
//         rank: 0,
//         name: "Heat/Chill",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: NA,
//         range: RANGES.sphere,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.shift,
//         description: "The air in a 15-foot radius around you becomes pleasantly warm or cool, providing a Boon to saves against extreme temperatures.",
//     },
//     {
//         rank: 0,
//         name: "Ignite/Snuff",
//         type: TYPES.arcane,
//         school: SCHOOLS.elementalism,
//         prerequisite: NA,
//         range: RANGES.close,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.gestureAndComponent,
//         duration: DURATIONS.permanent,
//         description: "You light or extinguish a candle, torch, or lantern within 30 feet. The flame persists as normal for the fuel source.",
//     },
//     {
//         rank: 0,
//         name: "Puff of Smoke",
//         type: TYPES.arcane,
//         school: SCHOOLS.elementalism,
//         prerequisite: NA,
//         range: RANGES.personal,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.gesture,
//         duration: DURATIONS.instant,
//         description: "An impressive puff of smoke erupts in front of you. Very popular for dramatic entrances and exits. Can give you a Boon to Stealth checks in certain situations as determined by the GM.",
//     },
//     {
//         rank: 1,
//         name: "Elemental Bolt",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "",
//         range: RANGES.medium,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "This spell send a bolt of elemental energy from your hand or focus at the target. The fireball can be dodged or parried as a ranged attack. The bolt inflicts 2d6 damage on hit. Each PL beyond the first increases damage by 1d6 or creates another bolt that hits another target within range.",
//     },
//     {
//         rank: 1,
//         name: "Frost",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "",
//         range: RANGES.sphere,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.stretch,
//         description: "You drastically lower the temperature around you in a 5-foot radius. All natural fires in the area of effect are extinguished. All living creatures in the AoE begin Freezing (per Extreme Temperature rules). The AoE is treated as Difficult Terrain. Each PL beyond the first increases the radius by 5 feet. Any water in the AoE freezes, causing full containers to burst and small floes to form in bodies of water. This spell has no effect on Monsters.",
//     },
//     {
//         rank: 1,
//         name: "Gust of Wind",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "",
//         range: RANGES.cone,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "This spell creates a great gust of wind. This gust takes the form of a 30-foot cone. All untethered objects and creatures up to medium size in the AoE are pushed 1d4 hexes away from you and suffer an equal amount of bludgeoning damage. Each PL beyond the first increases the number of dice rolled by one. This spell has no effect on creatures or objects larger than medium size.",
//     },
//     {
//         rank: 1,
//         name: "Pillar",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.shift,
//         description: "This spell raises a pillar from the earth. The pillar is 10 feet high per PL, and 3 feet on each side. If someone is standing in that spot, they must make an Acrobatics check (not an action) to avoid falling off the pillar. If the pilar impacts a ceiling, anyone caught between takes 2d6 damage.",
//     },
//     {
//         rank: 1,
//         name: "Shatter",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.word,
//         duration: DURATIONS.instant,
//         description: "By breaking the invisible bonds that hold physical matter together, you can shatter material objects. With spell, you inflict 2d10 damage on an inanimate and non-magical item. Any armor rating has no effect. Each PL beyond the first increases the damage by 1d10.",
//     },
//     {
//         rank: 2,
//         name: "Elemental Blast",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "Elemental Bolt",
//         range: RANGES.long,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "This spell sends a large elemental blast from your hand or focus at the target. The blast can be dodged or parried as a ranged attack. The blast inflicts 2d8 damage on a hit. Each PL beyond the first increases the damage by 1d8 or creates another blast that hits another target within range.",
//     },
//     {
//         rank: 2,
//         name: "Stone Shield",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "Pillar",
//         range: RANGES.personal,
//         castingTime: CASTING_TIMES.reaction,
//         requirements: REQUIREMENTS.gestureAndComponent,
//         duration: DURATIONS.instant,
//         description: "You hurl some pebbles to the ground in front of you to instantly summon a shield of stone that decreases the damage of an incoming attack by 2d6. Each PL beyond the first decreases the damage by an additional 1d6. You must cast this spell after the roll the hit, but before damage is rolled. This spell can be combined with armor.",
//     },
//     {
//         rank: 2,
//         name: "Stonewall",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "Pillar",
//         range: RANGES.close,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.shift,
//         description: "This spell raises a wall from the ground or a stone floor. This wall is 3 feet thick, 6 feet high, and 10 feet wide. Each PL beyond the first creates another segment of wall. If someone is standing on the spot where the wall is created, they must make an Acrobatics check (not an action) to avoid falling off. If the wall is created under a sufficiently lower ceiling, the victim takes 2d6 bludgeoning damage.",
//     },
//     {
//         rank: 2,
//         name: "Tidal Wave",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "Frost",
//         range: RANGES.cone,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.allThree,
//         duration: DURATIONS.instant,
//         description: "You summon a great wave from a water source within range. This wave takes the form of a 60-foot cone. The AoE starts at the source, not at yourself. All untethered objects and creatures in AoE are pushed 1d6 hexes away from the water source and suffer an equal amount of damage. Each PL beyond the first increases the number of dice rolled by one.",
//     },
//     {
//         rank: 2,
//         name: "Whirlwind",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "Gust of Wind",
//         range: RANGES.sphere,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: "This spell creates a mighty whirlwind around the mage. This whirlwind takes the form of a sphere with a 10-foot radius. All untethered objects and creatures up to and including medium size in the AoE are hurled 1d4 hexes away, suffer an equal amount of bludgeoning damage, and land prone. Each PL beyond the first increases the radius of the whirlwind by 10 feet and the number of dice rolled by one. You can choose the take a Bane on your casting roll in order to let one person in the AoE be hurled to another spot of your choice within the spell's range. You decide whether that person takes damage and whether they land prone.",
//     },
//     {
//         rank: 3,
//         name: "Firebird",
//         type: TYPES.both,
//         school: SCHOOLS.elementalism,
//         prerequisite: "Elemental Blast",
//         range: RANGES.long,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.wordAndGesture,
//         duration: DURATIONS.instant,
//         description: ".",
//     },
//     {
//         rank: 2,
//         name: "Magic Shield",
//         type: TYPES.both,
//         school: SCHOOLS.general,
//         prerequisite: "Protection From Magic or Dispel",
//         range: RANGES.close,
//         castingTime: CASTING_TIMES.reaction,
//         requirements: REQUIREMENTS.gesture,
//         duration: DURATIONS.instant,
//         description: "You interfere with a spell cast by another caster within 30 feet. This spell is a reaction and breaks the initiative order. You cast this spell after your opponent's roll to succeed, but before they roll for damage or other effect. If you succeed, the power level of your opponent's spell decreases by the power level at which you cast Magic Shield. If this reduces the power level to 0 or less, the spell has no effect. You can also use this spell to stop magical attacks from Monsters, in which case, each power level reduces the number of dice rolled for damage by 1.",
//     },
//     {
//         rank: 3,
//         name: "Transfer Power",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: "Magic Shield",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.action,
//         requirements: REQUIREMENTS.gesture,
//         duration: DURATIONS.instant,
//         description: "You transfer WP from or to another humanoid creature. You can transfer a number of WP up to four times the power level at which this spell is cast. If the target of this spell is unwilling, you get a Bane to your casting check. Your WP can never exceed your maximum or go below 0; the same goes for the target of this spell.",
//     },
//     {
//         rank: 4,
//         name: "Bind Spell",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: "Transfer",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.shift,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
//         duration: `${DURATIONS.permanent} (see description)`,
//         description: "You bind a spell to an inanimate object of your choice. The power level at which you cast Bind Spell determines the power level of the bound spell. Binding a magic trick requires power level 1. When casting Bind Spell, you also decide how the bound spell is activated. When the bound spell is activated, the spell uses WP from the person activating it. If that person cannot or will not spend their WP, the spell is not activated. Once a bound spell has been activated, the binding dissolves, unless Bind Spell is combined with Permanence. Bind Spell can be combined with Charge to give the object its own WP to use. The two spells must be cast consecutively.",
//     },
//     {
//         rank: 4,
//         name: "Charge",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: "Transfer",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.stretch,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
//         duration: DURATIONS.shift,
//         description: "You transfer your WP to an inanimate object of your choice, which then acts as a battery. Each power level at which you cast Charge lets you transfer up to 10 WP. Anyone in contact with the object can then use its WP instead of their own. After one Shift, the WP dissipates, unless combined with Permanence. Charge can also be combined with Bind Spell.",
//     },
//     {
//         rank: 5,
//         name: "Permanence",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: "Bind Spell",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.shift,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
//         duration: DURATIONS.permanent,
//         description: "This ritual is combined with another spell and makes it permanent. This costs the mage one point of WIL permanently (and reduces maximum WP by 1). The power level of Permanence must be equal to that of the spell being made permanent. Permanence cannot be added to spells with Instant duration. If Permanence is combined with Bind Spell, the latter becomes permanent and the bound spell can be activated any number of times.",
//     },
//     {
//         rank: 5,
//         name: "Permanence",
//         type: TYPES.arcane,
//         school: SCHOOLS.general,
//         prerequisite: "Bind Spell",
//         range: RANGES.touch,
//         castingTime: CASTING_TIMES.shift,
//         requirements: `${REQUIREMENTS.word}, ${REQUIREMENTS.gesture}`,
//         duration: DURATIONS.permanent,
//         description: "This ritual is combined with another spell and makes it permanent. This costs the mage one point of WIL permanently (and reduces maximum WP by 1). The power level of Permanence must be equal to that of the spell being made permanent. Permanence cannot be added to spells with Instant duration. If Permanence is combined with Bind Spell, the latter becomes permanent and the bound spell can be activated any number of times.",
//     },
// ];
